platform :ios, '14.5'
inhibit_all_warnings!
install! 'cocoapods',

:generate_multiple_pod_projects => true,
:incremental_installation => true,
:preserve_pod_file_structure => true,
:warn_for_unused_master_specs_repo => false

project 'shell.xcodeproj'
workspace 'Example.xcworkspace'

target 'shell' do
  use_frameworks!
  pod 'UIRouter/Web', :path => '../'
  pod 'Submodule', :path => 'Submodule/'
end

post_install do |installer|
  installer.pod_target_subprojects.flat_map { |p| p.targets }.each do |t|
    t.build_configurations.each do |c|
      if c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.5
        c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.5'
      end
    end
  end
end
